### ISSUE TITLE
Configure database automatically

### ISSUE THREAD

**Issue by ehmatthes** [ehmatthes/heroku-buildpack-python#8]
Migrating and using the db should fail, because I'm only using SQLite locally, and Heroku uses Postgres. Automatically install libraries needed to use postgres, and configure settings to use this db when on heroku.

**Comment by ehmatthes** [comment]
## Tasks

- [ ] Run migrate once just to confirm it fails.
- [ ] Add psycopg2 to requirements.txt if not already present.
- [ ] Modify settings.py to use Heroku postgres db.
  - [ ] Should be able to append these settings at the end, overriding any earlier local settings.

**Comment by ehmatthes** [comment]
Works!
